spring.application.name=CartService
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoint.health.enabled=true

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

server.port=8090