spring.application.name=CartService
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoint.health.enabled=true

server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m



spring.session.store-type=none
server.servlet.session.persistent=false
server.servlet.session.cookie.name=JSESSIONID

server.port=8090