apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app: cart-service
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-nodeport
  labels:
    app: cart-service
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30090
    protocol: TCP
    name: http
  selector:
    app: cart-service

